### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by ousi-fk** [modelica/VehicleInterfaces#116]
I am new to OpenModelica and was looking for OpenModelica car models and found this site.
I would like to simulate getting the following data, is it possible?
・Speed of a car
・Acceleration performance of a car
・Deceleration performance of a car
・Fuel consumption of a car,etc.
I could not find an appropriate place to ask this question, so I asked it here.
If there is another appropriate place, please let me know and I will move it.

**Comment by AHaumer** [comment]
First, please distinguish the language (and librairies) Modelica and tools (OpenModelica and many others). 
This repository is about vehicle interfaces a library maintained by the Modelica Association, The library can be used in OpenModelica or any other tool. If your questions are related to the tool OpenModelica, please go to [https://github.com/OpenModelica/](https://github.com/OpenModelica/).
Vehicle interfaces means the library provides a framework to enable people to develop models that fit together using the same interfaces, nearly no ready-to-use models of complete cars.
Since you ask for fuel consumption: Please note that detailed modeling and simulation of combustion engines is a tricky job.
A lot easier is the usage of electric drives for full electric cars. 
To answer your questions, you could use a commercial or open source library: [https://modelica.org/libraries.html](https://modelica.org/libraries.html)
For one-dimensional simulation of electric cars (i.e. neglecting 3D-effects, without steering) you could use the free library [EMOTH](https://github.com/modelica-3rdparty/EMOTH).

**Comment by ousi-fk** [comment]
Thank you very much.
I now understand that it is not easy to calculate fuel consumption.
I will try to make use of the library you mentioned, EMOTH.

**Comment by ousi-fk** [comment]
Thank you for the other day.
Since then, I have looked at the EMOTH library you referred me to and read the paper on EMOTH (https://ep.liu.se/ecp/132/030/ecp17132285.pdf).
In the paper, it was mentioned that "The modular concept allows to define independently a track with inclination and road surface, a vehicle and to try different designs of the drive and / or the battery.
I would like to derive the optimal vehicle for each driving cycle and track pattern when varying the driving cycle and track pattern.
How can I change the driving cycle and track pattern in a sample such as EMOTH.Example.TestWithThrottle?

**Comment by AHaumer** [comment]
Consider Examples.TestWithDriver:
Klick on drivingCycle and choose the drivingCycle or define your own.
Klick on inclinationData and define inclination either as constant or dependent on position along track.
Klick on rollingReistanceData and define rollingReistance either as constant or dependent on position along track.
Klick on track and define wind speed either as constant or as signal input.

**Comment by tobolar** [comment]
Please continue the discussion by opening a new issue directly on https://github.com/AHaumer/EMOTH.
