### ISSUE TITLE
Replace "fake" enumerations with enumerations in VehicleInterfaces.Types

### ISSUE THREAD

**Issue by harmanpa** [modelica/VehicleInterfaces#25]
The classes ``VehicleInterfaces.Types.GearMode`` and ``VehicleInterfaces.Types.IgnitionSetting`` use Integer constants and a choices annotation in order to behave like an enumeration. This is due to enumerations not being fully supported at the time of original development.

Enumerations are now generally supported in tools so these should be updated (at a major release).

**Comment by tobolar** [comment]
Actually, work on this issue shall be coupled with #28 as well.

The GearMode and IgnitionSetting are both used in `DriverEnvironments.Internal.StandardBus` which shall be reintroduced again. This StandardBus is marked obsolete in current v1.2.4 but this must be reverted in the next major version.
In contrast, busses in e.g. `DriverEnvironments.Interfaces` shall be marked obsolete and no more used.

**Comment by tobolar** [comment]
Well I have analysed this and it doesn't seem to be feasible at the moment. The problem is that the "enumerations" are mainly used in control busses. And to work with the busses in Diagrams would require particular graphical blocks for enumerations, which are not available. See also comment https://github.com/modelica/ModelicaStandardLibrary/issues/91#issuecomment-272549268.

It would be possible to use the enumeration for the parameter _selectedGearboxMode_ in driver models. But I see no benefit of doing so because then there have to be some transformation of enumeration parameter to integer on control bus. So rather tricky and confusing solution.
