### ISSUE TITLE
Load torque parameter description misleading

### ISSUE THREAD

**Issue by Claytex** [modelica/VehicleInterfaces#38]
Hi, in vehicle interfaces there is a model with path: VehicleInterfaces.Accessories.MinimalAccessories

The parameter 

  parameter Modelica.SIunits.Torque accessoriesLoad=2 
    "Total effective torque load due to the accessories (constant)

implies that you should provide a positive torque for the load. Within the model the torque sign should be made negative when used in the torque actuator otherwise this model actually converts a torque load to a torque gain.

It is my suggestion that the torque actuator should reference -accessoriesLoad rather than accessoriesLoad.

Many thanks,
Alex

**Comment by tobolar** [comment]
I think this is reasonable. But for this update we definitely need a conversion script.

So we can upgrade the model for the next major version as follows:
1. `torqueLoss` must be of `Modelica.Mechanics.Rotational.Sources.SignTorque` (probably with linear regularization for speed around zero) instead of `ConstantTorque`. As long as connected to an ICE, this would probably not be noticeable but I guess this is a good modelling practice since we really deal with a load which is speed sign dependent.
1. Rename parameter `accessoriesLoad` to `tau_load`.
1. Prepare conversion script for: accessoriesLoad -> -tau_load
1. The examples in `VehicleInterfaces.Examples` will deliver another but correct results.
1. This will be referred in the release notes.
