### ISSUE TITLE
MultiBodyEnd purpose

### ISSUE THREAD

**Issue by rocomanmelli** [modelica/VehicleInterfaces#40]
I would like to understand why MultiBodyEnd blocks are needed (for example, in the chassis of the FrontWheelDriveManualVehicle) since they just add zero force and torque... Were they intended to allow simulation of isolated components of models?

**Comment by tobolar** [comment]
To my understanding, the reason is the possibility to mix 1D and 3D assemblies in vehicle architectures. Probably the most common case is a 1D driveline connected to a multibody chassis. Then, the `wheelHub_i` connectors of both assemblies must be of the same structure, enabling multibody `wheelHub_i.bearingFrame` as a subconnector to connect 3D mechnics. In that case, the MultiBodyEnd(s) on the 1D driveline's side assures the ballance of 3D forces and torques which are principally not a part of 1D models.

To control the availability of the bearingFrame in MultiBodyEnd in the assemblies of VI, there exist two groups of boolean parameters. When designing a component, boolean parameters starting with "include" shall be used by designer. For example, you can find `includeWheelBearings=false` in 1D driveline models. Thus, the `wheelHub_i` connectors of such models contain only 1D `flange` subconnector.
 When such model is used in the architecture, the parameter(s) starting with "using" shall be set depending on the structure of connected assembles. 
When e.g. the 1D driveline is connected to a 3D chassis (or brake model; having `includeWheelBearings=true`), the following must be set: `driveline.usingMultiBodyChassis=true`.

Unfortunately, there is no example demonstrating this behaviour in VI since only 1D models are used there.

**Comment by tobolar** [comment]
Update: there is a 3D chassis `VehicleInterfaces.Chassis.MinimalChassis3` used e.g. in `VehicleInterfaces.Examples.FrontWheelDriveManualVehicle`. Check there the corresponding parameters of driveline and brakes!
